### PR TITLE
Aka tutorial

### PR DESCRIPTION
**Pull request by Alihan26**
# Pull Requests Checklist

Assignee:

- \[x\] code commented?
- \[x\] deactivated things not needed? (e.g. other features which only were prepared)
  - \[ \] alerts that this is todo?
- \[x\] test run localhost?
- \[x\] tested manually all features and edge cases?
- \[ \] documentation added / updated?
- \[x\] pre-commit checks passed?
- \[x\] pipelines passed?

Reviewer:

- \[ \] correct branch?
- \[ \] are there any code smells?
- \[ \] did pipeline pass?
- \[ \] is the code well documented?
- \[ \]tested manually all features and edge cases?

### CODE REVIEW

**Comment by B1s9l** [comment]
- Please Implement a button in the profile "Tutorial" that navigates to the overview page and start the tutorial over (using "navigate("/teams?showTutorial=true");" should work)
- Change the tutorial background color, i would make the background 100% transparent and blur everythign behind it (backdrop-filter: blur(10px); or something like that) if you do that, dont forget to also remove the containers dropshadow and visible border

**Comment by Alihan26** [comment]
Hey guys (@B1s9l , @Monti934 ), it checks the tests, and the implementation is thus finished, please tell me if there's something missing, thanks!

**Comment by Alihan26** [comment]
All the adjustments have been made, ready to merge @B1s9l @Monti934

**Review by Monti934 — CHANGES_REQUESTED** [review]
add new line before return statement 
Profile.tsx line 70

**Review by Monti934 — APPROVED** [review]

**Pull request merged**
